[package]
name = "TRPL_03_03_function_statement_expression"
version = "0.1.0"
authors = ["liuchen <liuchen@davdian.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
